language: android

android:
  components:
  # Use the latest revision of Android SDK Tools.
  - tools
  - platform-tools

  # The BuildTools version used by your project.
  # Keep in sync with buildToolsVersion in app/build.gradle.
  # To list all supported versions:
  # $ tools/android list sdk --extended --all
  # (look for a string: id: XX or "build-tools-A.B.C")
  - build-tools-24.0.3

  # The SDK version used to compile your project.
  # Keep in sync with compileSdkVersion in app/build.gradle.
  - android-24

  # For AppCompat.
  - extra

  # For emulator. Cannot use x86 w/o HW acceleration, which is provided by KVM.
  # Keep in sync with the SDK version above.
  # To list all supported images:
  # $ cd android-sdk-linux; tools/android list sdk --extended --all
  # (look for a string: sys-img-XX-android-YY)
  # Currently, there's no image for API level 24 with ARM EABI.
  - sys-img-armeabi-v7a-android-24

# Emulator Management: Create, Start and Wait
before_script:
# Keep -t and --abi in sync with the image version above.
# To list all supported ABIs:
# $ cd android-sdk-linux; tools/android list target
# for "-t", look for: id: XX or "android-YY".
# for "--abi", use one of "Tag/ABIs" on that id.
- echo no | android create avd --force -n test -t android-24 --abi default/armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
# Ping the emulator to make sure it's up
- adb shell input keyevent 82 # KEYCODE_MENU

after_script:
- pip install --user gsutil
- cd app/build
# Build a poor man's index
- echo
  "<h1>Artifacts for <a href=https://github.com/${TRAVIS_REPO_SLUG?}/compare/${TRAVIS_COMMIT_RANGE?}>commit ${TRAVIS_COMMIT?}</a></h1><pre>"
  >index.html
- find . -type f -exec echo "<a href='{}'>{}</a>" \; | grep -E '\.htm|\.apk' | sort >>index.html
# Upload build artifacts to GCS
- ARTIFACTS_PATH=${GSUTIL_BUCKET?}/${TRAVIS_REPO_SLUG?}/${TRAVIS_PULL_REQUEST/false/${TRAVIS_BRANCH?}}
- gsutil -m
  -o "Credentials:gs_oauth2_refresh_token=${GSUTIL_TOKEN?}"
  -o "GSUtil:default_project_id=${GSUTIL_PROJECT?}"
  rsync -d -r . "gs://${ARTIFACTS_PATH?}"
- echo "Artifacts uploaded to http://${ARTIFACTS_PATH?}"

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

jdk:
- oraclejdk8

branches:
  only:
  - master
